blank_issues_enabled: false
contact_links:
  - name: Question or Help
    url: https://github.com/yourusername/youtube-automation/discussions
    about: Ask questions and get help from the community
  - name: Feature Discussion
    url: https://github.com/yourusername/youtube-automation/discussions/categories/ideas
    about: Discuss ideas for new features
  - name: Documentation
    url: https://docs.yourdomain.com
    about: Check our documentation for guides and examples
